>P1; sequence of: /var
 
 PFTNVSCTTSKECWSVCQRLHNTSRGKCMNKKCRCYS                       
 PFTNVSCTTSKECWSVCQRLHNTSRGKCMNKKCRCYS                       
 PFTNVSCTTSKECWSVCQRLHNTSRGKCMNKKCRCYS                       
 PFTNVSCTTSKECWSVCQRLHNTSRGKCMNKKCRCYS                       
 PFTNVSCTTSKECWSVCQRLHNTSRGKCMNKKCRCYS                       
 PFTNVSCTTSKECWSVCQRLHNTSRGKCMNKKCRCYS                       
 PFTNVSCTTSKECWSVCQRLHNTSRGKCMNKKCRCYS                       
 PFTNVSCTTSKECWSVCQRLHNTSRGKCMNKKCRCYS                       
 PFTNVSCTTSKECWSVCQRLHNTSRGKCMNKKCRCYS                       
 PFTNVSCTTSKECWSVCQRLHNTSRGKCMNKKCRCYS                       
 PFTNVSCTTSKECWSVCQRLHNTSRGKCMNKKCRCYS                       
 PFTNVSCTTSKECWSVCQRLHNTSRGKCMNKKCRCYS                       
 *                                                           
