>P1; sequence of: /var
 
 ALHWRAAGAATVLLVIVLLAGSYLAVLAERGAPGAQLITYPRALWWSVETATTVGYGDLY
 PVTLWGRCVAVVVMVAGITSFGLVTAALATWFVGREQ                       
 ALHWRAAGAATVLLVIVLLAGSYLAVLAERGAPGAQLITYPRALWWSVETATTVGYGDLY
 PVTLWGRCVAVVVMVAGITSFGLVTAALATWFVGREQ                       
 ALHWRAAGAATVLLVIVLLAGSYLAVLAERGAPGAQLITYPRALWWSVETATTVGYGDLY
 PVTLWGRCVAVVVMVAGITSFGLVTAALATWFVGREQ                       
 ALHWRAAGAATVLLVIVLLAGSYLAVLAERGAPGAQLITYPRALWWSVETATTVGYGDLY
 PVTLWGRCVAVVVMVAGITSFGLVTAALATWFVGREQ                       
 *                                                           
